import { useState } from "react";
import { useUser } from "@clerk/clerk-react";
import {
  FinancialRecord,
  useFinancialRecords,
} from "@/contexts/financial-record-context";
import { motion } from "framer-motion";

// Conversion rates based on 1 NPR (You can later fetch these from an API)

const FinancialRecordForm = () => {
  const [description, setDescription] = useState<string>("");
  const [amount, setAmount] = useState<number>(0); // In selected currency (NPR)
  const [category, setCategory] = useState<string>("");
  const [paymentMethod, setPaymentMethod] = useState<string>("");
  const [currency, setCurrency] = useState<string>("NPR");

  const { addRecord } = useFinancialRecords();
  const { user } = useUser();

  // Since we're only using NPR, no conversion needed
  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    if (!user) {
      alert("User not authenticated!");
      return;
    }

    const parsedAmount =
      typeof amount === "string" ? parseFloat(amount) : amount;
    if (isNaN(parsedAmount) || parsedAmount <= 0) {
      alert("Please enter a valid amount.");
      return;
    }

    if (!category || !paymentMethod) {
      alert("Please select a category and payment method.");
      return;
    }

    const newRecord: FinancialRecord = {
      _id: "", // This will be generated by the server
      userId: user.id,
      date: new Date(),
      description,
      amount: parsedAmount,
      category,
      paymentMethod,
      currency,
    };

    addRecord(newRecord);

    // Reset fields
    setDescription("");
    setAmount(0);
    setCategory("");
    setPaymentMethod("");
    setCurrency("NPR");
  };
  return (
    <motion.div
      initial={{ opacity: 0, y: 40 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: 40 }}
      transition={{ duration: 0.4, ease: "easeOut" }}
      className="w-full max-w-2xl mx-auto mt-6 sm:mt-10 px-4 sm:px-6 lg:px-8"
    >
      <form
        onSubmit={handleSubmit}
        className="bg-white mb-4 rounded-3xl shadow-lg p-5 sm:p-7 md:p-9 space-y-6 border border-gray-100"
      >
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 sm:gap-4">
          <h2 className="text-xl sm:text-2xl md:text-3xl font-bold text-gray-900 shrink-0">
            New Record
          </h2>
          <div className="flex flex-col sm:flex-row items-between sm:items-center gap-1 sm:gap-2 md:gap-4 text-xs sm:text-sm font-medium text-gray-800 overflow-hidden">
            <span className="whitespace-nowrap truncate">
              {new Date().toLocaleDateString()}
            </span>
            <span className="whitespace-nowrap truncate">
              {new Date().toLocaleTimeString()}
            </span>
          </div>
        </div>

        {/* Description */}
        <div className="relative">
          <label className="block text-sm font-medium text-gray-700 mb-1.5">
            Description
          </label>
          <input
            type="text"
            required
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            className="w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-xl text-sm sm:text-base focus:ring-2 focus:ring-teal-500 focus:border-transparent transition-all duration-200"
            placeholder="e.g., Grocery shopping"
          />
        </div>

        {/* Currency & Amount */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          {/* Currency */}
          <div className="relative">
            <label className="block text-sm font-medium text-gray-700 mb-1.5">
              Currency
            </label>
            <select
              value={currency}
              onChange={(e) => setCurrency(e.target.value)}
              className="w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-xl text-sm sm:text-base focus:ring-2 focus:ring-teal-500 focus:border-transparent appearance-none transition-all duration-200"
            >
              <option value="NPR">NPR (₨)</option>
            </select>
          </div>

          {/* Amount */}
          <div className="relative">
            <label className="block text-sm font-medium text-gray-700 mb-1.5">
              Amount (NPR)
            </label>
            <input
              type="number"
              required
              value={amount}
              onChange={(e) => setAmount(parseFloat(e.target.value))}
              className="w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-xl text-sm sm:text-base focus:ring-2 focus:ring-teal-500 focus:border-transparent transition-all duration-200"
              placeholder="e.g., 100"
            />
          </div>
        </div>

        {/* Category */}
        <div className="relative">
          <label className="block text-sm font-medium text-gray-700 mb-1.5">
            Category
          </label>
          <select
            required
            value={category}
            onChange={(e) => setCategory(e.target.value)}
            className="w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-xl text-sm sm:text-base focus:ring-2 focus:ring-teal-500 focus:border-transparent appearance-none transition-all duration-200"
          >
            <option value="">Choose a category</option>
            <option value="Food">Food</option>
            <option value="Rent">Rent</option>
            <option value="Salary">Salary</option>

            <option value="Utilities">Utilities</option>
            <option value="Entertainment">Entertainment</option>
            <option value="Part Time Job">Part Time Job</option>
            <option value="Clothes">Clothes</option>
            <option value="Other">Other</option>
          </select>
        </div>

        {/* Payment Method */}
        <div className="relative">
          <label className="block text-sm font-medium text-gray-700 mb-1.5">
            Payment Method
          </label>
          <select
            required
            value={paymentMethod}
            onChange={(e) => setPaymentMethod(e.target.value)}
            className="w-full px-4 py-3 bg-gray-50 border border-gray-200 rounded-xl text-sm sm:text-base focus:ring-2 focus:ring-teal-500 focus:border-transparent appearance-none transition-all duration-200"
          >
            <option value="">Choose payment method</option>
            <option value="Credit Card">Credit Card</option>
            <option value="Cash">Cash</option>
            <option value="Bank Transfer">Bank Transfer</option>
          </select>
        </div>

        {/* Submit Button */}
        <button
          type="submit"
          className="w-full py-3 sm:py-4 bg-teal-600 text-white text-sm sm:text-base font-semibold rounded-xl hover:bg-teal-700 focus:ring-4 focus:ring-teal-200 transition-all duration-200 shadow-md hover:shadow-lg"
        >
          Add Record
        </button>
      </form>
    </motion.div>
  );
};

export default FinancialRecordForm;
